### ISSUE TITLE
Add sound effect not only for start/stop voice message but also for sending message

### ISSUE THREAD

**Issue by DraganRatkovich** [sulaiman-alqusaimi/whatsapp_enhansements#1]
Hello,
@sulaiman-alqusaimi If possible, add a sound effect not only for recording and stopping a voice note, but also for sending voice and text messages. That is, when the recording of a voice note is finished, the sending sound should play, and also for text messages, this sound should play.
I can provide you with a sound effect if you like, it's very easy to find.

**Comment by rexya2017** [comment]
I think it will be added by WhatsApp beta developers soon. if you go to the directory C:\Program Files\WindowsApps\5319275A.51895FA4EA97F_2.2221.4.0_x64__cv1g1gvanyjgm\Sounds, the sound is already available. We just have to wait. :)

**Comment by DraganRatkovich** [comment]
@rexya2017 Thanks for the info, I didn't check the WhatsAppBeta installation directory. They also have to add the start/stop sound of the voice message recording, because currently the addon is using the old sound which is a little messy, the new sounds are much better.

**Comment by rexya2017** [comment]
I agree with you regarding this. :)

Pada tanggal Min, 5 Jun 2022 pukul 12.29 DraganRatkovich <
***@***.***> menulis:
