### ISSUE TITLE
Add shortcuts for quick reaction to a message

### ISSUE THREAD

**Issue by DraganRatkovich** [sulaiman-alqusaimi/whatsapp_enhansements#7]
Hello,
As you may already know, WhatsApp recently made message reactions available in the UWP version of its app, so there are six reactions available at the time of this writing.
It would be more convenient if you added a keyboard shortcut to these six reactions to quickly react to the focused message, instead of opening the context menu, finding the reaction menu and choosing the desired reaction from this menu.
@MuhammadGagah Maybe you can collaborate on this?

**Comment by MuhammadGagah** [comment]
hi @DraganRatkovich I have tried it, but it still doesn't work.

**Comment by DraganRatkovich** [comment]
@sulaiman-alqusaimi
